# This file includes an example of using resource requests
# as a method to target specific nodes
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: limited
  name: limited
spec:
  containers:
  - image: httpd
    name: limited
    resources:
      requests:
        memory: "100Mi"
        cpu: "1Gi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
